name: mobile_griya_gede_mundeh
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_flavor: ^3.1.3
  flutter_hooks: null
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hooks_riverpod: ^3.0.0-dev.3
  intl: any
  json_annotation: ^4.9.0
  riverpod_annotation: ^3.0.0-dev.3
  shimmer: ^3.0.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  build_runner: null
  custom_lint: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - .env
    - .env.dev
